### ISSUE TITLE
Non récupération de la date et de l'heure à l'initialisation

### ISSUE THREAD

**Issue by laurentuof** [UBO-Open-factory/foodrest#21]
En mode usine 

.....

****************************************************
*     FOOD REST : Initialisation de l'horloge      *
****************************************************

Connection au serveur de temps...
OK.
**Il est : 01:00:05
Nous sommes le : 1/1/1970**

**Comment by AlexP20000** [comment]
En fait cela fonctionne mais pas derrière un proxy, comme celui qu'il y a à l'UBO. Heureusement il y a un serveur de temps.
J'ai donc fait un questionnement sur le serveur de temps local et si ça ne fonctionne pas on va chercher le temps sur un serveur public.
